const pks = require("../controllers/pks")
const upload = require("../controllers/uploadFile")
const express = require("express")
const user = require('../controllers/user')
const classSurvey = require('../controllers/class')
const router = express.Router()

router.route('/getpks')
    .get(pks.getPks)
router.route('/pks/edit')
    .post(pks.editTitle)
router.route('/pks/addValueOfTitle')
    .post(pks.addValueOfTitle)
router.route('/pks/deleteValueOfTitle')
    .post(pks.deleteValueOfTitle)
router.route('/uploadExcel')
    .post(upload.single("kuri-file"), upload.uploadFile)
router.route('/account/register')
    .post(user.createAccount)
router.route('/account/getUser')
    .post(user.getUser)
router.route('/account/deleteUser')
    .post(user.deleteAccount)
router.route('/account/editUser')
    .post(user.editAccount)
router.route('/classSurvey/getAll')
    .get(classSurvey.getListClass)
router.route('/classSurvey/xoaClass')
    .post(classSurvey.xoaClass)
router.route('/pks/createCuocKs/:mamonhoc')
    .get(pks.createCuocKs)
router.route('/pks/getAllKQKS')
    .get(pks.getALLKQKS)
router.route('/pks/xoaKS')
    .post(pks.xoaKS)
router.route('/pks/getKQKS')
    .post(pks.getKQKS)
router.route('/pks/ketThucKS')
    .post(pks.ketThucKS)
router.route('/pks/getAllKSActive')
    .get(pks.getAllKsActive)
module.exports = router